[[characters]]
name = "ducc"
  [[characters.tasks]]
  name = "DepositInventory"
  condition = "FullInventory"
  [[characters.tasks]]
  name = "MineIron"

[[characters]]
name = "ducc2"
  [[characters.tasks]]
  name = "DepositInventory"
  condition = "FullInventory"
  [[characters.tasks]]
  name = "MineCopper"

[[characters]]
name = "ducc3"
  [[characters.tasks]]
  name = "DepositInventory"
  condition = "FullInventory"
  [[characters.tasks]]
  name = "KillChickens"

[[characters]]
name = "ducc4"
  [[characters.tasks]]
  name = "DepositInventory"
  condition = "FullInventory"
  [[characters.tasks]]
  name = "KillChickens"

[[characters]]
name = "ducc5"
  [[characters.tasks]]
  name = "DepositInventory"
  condition = "FullInventory"
  [[characters.tasks]]
  name = "MineIron"
